import { useEffect, useState } from "react";

/**
 * Optional district-project pins for the embed's district-wide view.
 *
 * `public/data/cd2-projects.json` is generated by a separate offline script and may not exist
 * (a 404), may not be JSON (an HTML error page from a misconfigured host), or may be JSON that
 * doesn't match the expected shape. Every one of those must leave the embed rendering normally
 * with no pins and no console error -- this loader is the one place that boundary is enforced.
 */

export interface EmbedProject {
  id: string;
  title: string;
  category: string;
  latitude: number;
  longitude: number;
  url: string | null;
}

export interface EmbedProjectsPayload {
  generatedAt: string;
  districtId: number;
  projects: EmbedProject[];
}

const PROJECTS_PATH = "data/cd2-projects.json";

/** Same URL construction as `cd2Assets.ts`'s `assetUrl`, so BASE_URL is honoured. */
function projectsUrl(): string {
  return new URL(PROJECTS_PATH, window.location.origin + import.meta.env.BASE_URL).toString();
}

function readString(value: unknown): string | null {
  return typeof value === "string" && value.trim().length > 0 ? value : null;
}

function readFiniteNumber(value: unknown): number | null {
  return typeof value === "number" && Number.isFinite(value) ? value : null;
}

/** Only http(s) is kept as a link, same rule `cd2Assets.ts`'s `readUrl` applies to civic assets. */
function readHttpUrl(value: unknown): string | null {
  const text = readString(value);
  return text && /^https?:\/\//i.test(text) ? text : null;
}

/**
 * One malformed project is dropped rather than failing the whole payload -- a single bad row in
 * an otherwise valid snapshot shouldn't cost every other pin.
 */
function readProject(raw: unknown): EmbedProject | null {
  if (!raw || typeof raw !== "object") {
    return null;
  }
  const record = raw as Record<string, unknown>;
  const id = readString(record.id);
  const title = readString(record.title);
  const category = readString(record.category);
  const latitude = readFiniteNumber(record.latitude);
  const longitude = readFiniteNumber(record.longitude);
  if (!id || !title || !category || latitude === null || longitude === null) {
    return null;
  }
  return { id, title, category, latitude, longitude, url: readHttpUrl(record.url) };
}

/**
 * `null` for a missing/malformed top-level payload; a valid payload with zero or partially
 * malformed rows still returns its well-formed projects.
 */
function parsePayload(raw: unknown): EmbedProjectsPayload | null {
  if (!raw || typeof raw !== "object") {
    return null;
  }
  const record = raw as Record<string, unknown>;
  const generatedAt = readString(record.generated_at);
  const districtId = readFiniteNumber(record.district_id);
  if (!generatedAt || districtId === null || !Array.isArray(record.projects)) {
    return null;
  }
  const projects = record.projects
    .map(readProject)
    .filter((project): project is EmbedProject => project !== null);
  return { generatedAt, districtId, projects };
}

/**
 * Per-session promise memo, in the same spirit as `loadDistrictAssetsOnce`. Resolves to `null`
 * on any failure rather than rejecting -- there is no error state for this optional layer, only
 * "pins" or "no pins".
 */
let cached: Promise<EmbedProjectsPayload | null> | null = null;

export function resetEmbedProjectsCacheForTests(): void {
  cached = null;
}

export function loadEmbedProjectsOnce(): Promise<EmbedProjectsPayload | null> {
  if (cached) {
    return cached;
  }
  cached = fetch(projectsUrl())
    .then((response) => {
      if (!response.ok) {
        return null;
      }
      return response
        .json()
        .then((body) => parsePayload(body))
        .catch(() => null);
    })
    .catch(() => null);
  return cached;
}

/**
 * `null` while loading and whenever the snapshot is unavailable or malformed -- the district
 * view then simply renders with no project pins, per the "build and test the no-file path
 * first" instruction this loader exists to satisfy.
 */
export function useEmbedProjects(enabled: boolean): EmbedProjectsPayload | null {
  const [payload, setPayload] = useState<EmbedProjectsPayload | null>(null);

  useEffect(() => {
    if (!enabled) {
      setPayload(null);
      return;
    }
    let ignore = false;
    loadEmbedProjectsOnce().then((result) => {
      if (!ignore) {
        setPayload(result);
      }
    });
    return () => {
      ignore = true;
    };
  }, [enabled]);

  return payload;
}
